Feature/cadsify
ecmwf-projects/cads-toolbox pull request #14
Opened 2022-12-08 16:42 UTC by EddyCMWF

Still working on this, but creating the PR for some nice visuals and to keep track of conversations

2022-12-08 16:42 UTC, FussyDuck commented
[![CLA assistant check](http://claassistant.ecmwf.int:80/pull/badge/not_signed)](http://claassistant.ecmwf.int:80/ecmwf-projects/cads-toolbox?pullRequest=14) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf-projects/cads-toolbox?pullRequest=14) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: JamesVarndell<br/>:x: EddyCMWF<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf-projects/cads-toolbox?pullRequest=14) it.</sub>

2023-01-03 15:10 UTC, JamesVarndell requested changes
These changes look great! I've made a few specific suggestions, but I also have a couple of more general suggestions:

1. Consider renaming `inputs_transform` to use a private namespace (e.g. `_inputs_transform`, as no user should be accessing this module directly. If you do make this change, you can also remove leading underscores from the functions within `_inputs_transform`.
2. You've got nice tests for transforming kwargs in functions with arg types set, but none for the magic named input variables (e.g. "dataarray"). It would be nice to add a test for this case.

2023-01-03 15:10 UTC, JamesVarndell commented on tests/test_10_inputs_transform.py
> +    assert type(transformed) == xr.Dataset
```suggestion
    assert isinstance(transformed, xr.Dataset)
```

2023-01-03 15:10 UTC, JamesVarndell commented on tests/test_10_inputs_transform.py
> +    assert type(value) == np.ndarray
```suggestion
    assert isinstance(value, np.ndarray)
```

2023-01-03 15:10 UTC, JamesVarndell commented on tests/test_10_inputs_transform.py
> +    assert type(value) == xr.Dataset
```suggestion
    assert isinstance(value, xr.Dataset)
```

2023-01-03 15:10 UTC, JamesVarndell commented on tests/test_10_inputs_transform.py
> +    assert type(value) == xr.DataArray
```suggestion
    assert isinstance(value, xr.DataArray)
```

2023-01-03 15:10 UTC, JamesVarndell commented on tests/test_10_inputs_transform.py
> +    assert type(value) == pd.DataFrame
```suggestion
    assert isinstance(value, pd.DataFrame)
```

2023-01-04 11:12 UTC, EddyCMWF commented on cads_toolbox/cadsify.py
> +    return emohawk.transform(thing, kwarg_type)
Update made

2023-01-04 11:13 UTC, EddyCMWF commented on cads_toolbox/cadsify.py
> +                kwargs[key] = transform(value, kwarg_types[0])
done

2023-01-04 11:17 UTC, EddyCMWF commented on cads_toolbox/cadsify.py
> +    def wrapper(*args, **kwargs):
I'd prefer not to as then it is clear that `wrapper` is just the wrapper decorator and _wrapper handles the kwarg_types

2023-01-04 11:18 UTC, JamesVarndell approved these changes

2023-01-04 11:25 UTC, merged